### ISSUE TITLE
Unable to run after clean install

### ISSUE THREAD

**Issue by samuelhwilliams** [jayclassless/tidypy#28]
Hi,

This project looks super interesting. Unfortunately, I tried installing and running it, and it seems that `tidypy` has some conflicting dependencies/sub-dependencies.

Any advice would be greatly appreciated!

```aa:~/git/repo [branch]$ deactivate
aa:~/git/repo [branch]$ rmvirtualenv repo
Removing repo...
aa:~/git/repo [branch]$ mkvirtualenv repo
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.7'
New python executable in /Users/aa/.virtualenvs/repo/bin/python3.7
Also creating executable in /Users/aa/.virtualenvs/repo/bin/python
Installing setuptools, pip, wheel...workon done.
dvirtualenvwrapper.user_scripts creating /Users/aa/.virtualenvs/repo/bin/predeactivate
virtualenvwrapper.user_scripts creating /Users/aa/.virtualenvs/repo/bin/postdeactivate
virtualenvwrapper.user_scripts creating /Users/aa/.virtualenvs/repo/bin/preactivate
virtualenvwrapper.user_scripts creating /Users/aa/.virtualenvs/repo/bin/postactivate
virtualenvwrapper.user_scripts creating /Users/aa/.virtualenvs/repo/bin/get_env_details
ig	aa:~/git/repo [branch]$ workon repo
aa:~/git/repo [branch]$ which python
/Users/aa/.virtualenvs/repo/bin/python
aa:~/git/repo [branch]$ pip list
piPackage    Version
---------- -------
pip        18.1
setuptools 40.4.3
wheel      0.32.2
p aa:~/git/repo [branch]$ pip install tidypy
Collecting tidypy
  Using cached https://files.pythonhosted.org/packages/80/ef/4d74ccf0db57ee619cede7c4672d59551b4d0bf283a4fd7fa7877443a514/tidypy-0.6.0-py2.py3-none-any.whl
Collecting tqdm<5,>=4.11 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/91/55/8cb23a97301b177e9c8e3226dba45bb454411de2cbd25746763267f226c2/tqdm-4.28.1-py2.py3-none-any.whl
Collecting pydiatra<0.13,>=0.12.2 (from tidypy)
Collecting basicserial<0.2,>=0.1 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/80/6f/0da8ffa2fc03f122539cc42581e1736c98fb5021d7e362e7911b77e27494/basicserial-0.1.0-py2.py3-none-any.whl
Collecting pyroma<3,>=2.2 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/63/26/6a894d85cd510ed59c991d4b64d025308e1ee1294251e88aadbdd5659c0b/pyroma-2.4-py2.py3-none-any.whl
Collecting detect-secrets<0.11,>=0.9.1 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/57/03/db1ea045e762b4f7269653549225332eb48c9199876f094d190c3efd8968/detect_secrets-0.10.4-py2.py3-none-any.whl
Collecting pyyaml<5,>=3.12 (from tidypy)
Collecting check-manifest<0.38,>=0.37 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/7a/6a/a723e3a5b2844f47a522013738fea914c9f68d1ef576c97238409bd42e84/check_manifest-0.37-py2.py3-none-any.whl
Collecting pyflakes<1.7,>=1.5 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/d7/40/733bcc64da3161ae4122c11e88269f276358ca29335468005cb0ee538665/pyflakes-1.6.0-py2.py3-none-any.whl
Collecting restructuredtext-lint<2,>=1.1 (from tidypy)
Collecting dennis<1,>=0.9 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/2d/2e/2cb43a5e787387b558d2eeefc2713305d2df97c4622cee37b1e6f5505031/dennis-0.9-py2.py3-none-any.whl
Collecting click<8,>=6 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting vulture<0.30,>=0.25 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/1b/40/92d0b666eaa19bd5aa81a5fc066841f43e7ff140b17eaababb27c5782b4d/vulture-0.29-py2.py3-none-any.whl
Collecting demjson<3,>=2.2.4 (from tidypy)
Collecting six (from tidypy)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting pytoml<0.2,>=0.1 (from tidypy)
Collecting pydocstyle<3,>=2 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/43/8a/f1141af0c8406788a5c38ad5001d4163d903b5384a6517239d2ac42734c8/pydocstyle-2.1.1-py3-none-any.whl
Collecting pycodestyle<2.4,>=2.3 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/e4/81/78fe51eb4038d1388b7217dd63770b0f428370207125047312886c923b26/pycodestyle-2.3.1-py2.py3-none-any.whl
Collecting yamllint<2,>=1.8 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/c5/9c/2d1977d1898caf4133dab2b3a9668e3437d96a3ce09979bc996dfcd231e9/yamllint-1.12.1-py2.py3-none-any.whl
Collecting pep8-naming<0.8,>=0.4 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/39/bb/a34544c789e7e5458ed2db6cbd1c8e227bb01e4ce03a0b15ec4ec93e486d/pep8_naming-0.7.0-py2.py3-none-any.whl
Collecting pylint<2.2,>=2; python_version >= "3.4" (from tidypy)
  Using cached https://files.pythonhosted.org/packages/6e/c2/1e97c238877b6a86562d32297eb33a6670b6220e8ec0ca85f67b66dc893f/pylint-2.1.1-py3-none-any.whl
Collecting requests<3,>=2 (from tidypy)
  Downloading https://files.pythonhosted.org/packages/f1/ca/10332a30cb25b627192b4ea272c351bce3ca1091e541245cccbace6051d8/requests-2.20.0-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 1.2MB/s
Collecting bandit<2,>=1.4 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/da/94/34afbe0c28b0c35f5116955c86c20599b3c732ddc1b2c452f190760ebfbf/bandit-1.5.1-py2.py3-none-any.whl
Collecting mccabe<0.7,>=0.6 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting iso8601 (from basicserial<0.2,>=0.1->tidypy)
  Using cached https://files.pythonhosted.org/packages/ef/57/7162609dab394d38bbc7077b7ba0a6f10fb09d8b7701ea56fa1edc0c4345/iso8601-0.1.12-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /Users/aa/.virtualenvs/repo/lib/python3.7/site-packages (from pyroma<3,>=2.2->tidypy) (40.4.3)
Collecting docutils (from pyroma<3,>=2.2->tidypy)
  Using cached https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl
Collecting unidiff (from detect-secrets<0.11,>=0.9.1->tidypy)
  Using cached https://files.pythonhosted.org/packages/68/52/c7278fc3c17d1aaade84597968d88f97f0f4ec7288ddedb6970a341c5170/unidiff-0.5.5-py2.py3-none-any.whl
Collecting polib>=1.0.8 (from dennis<1,>=0.9->tidypy)
  Using cached https://files.pythonhosted.org/packages/30/a2/e407c3b00cace3d7fc8df14d364deeecfeb96044e1a317de583bc26eae58/polib-1.1.0-py2.py3-none-any.whl
Collecting snowballstemmer (from pydocstyle<3,>=2->tidypy)
  Using cached https://files.pythonhosted.org/packages/d4/6c/8a935e2c7b54a37714656d753e4187ee0631988184ed50c0cf6476858566/snowballstemmer-1.2.1-py2.py3-none-any.whl
Collecting pathspec>=0.5.3 (from yamllint<2,>=1.8->tidypy)
Collecting flake8-polyfill<2,>=1.0.2 (from pep8-naming<0.8,>=0.4->tidypy)
  Using cached https://files.pythonhosted.org/packages/86/b5/a43fed6fd0193585d17d6faa7b85317d4461f694aaed546098c69f856579/flake8_polyfill-1.0.2-py2.py3-none-any.whl
Collecting astroid>=2.0.0 (from pylint<2.2,>=2; python_version >= "3.4"->tidypy)
  Using cached https://files.pythonhosted.org/packages/19/92/6f6d3591c429dbdb31c18d8476ba1af08d5973d7cc09f66346109e9de7fb/astroid-2.0.4-py3-none-any.whl
Collecting isort>=4.2.5 (from pylint<2.2,>=2; python_version >= "3.4"->tidypy)
  Using cached https://files.pythonhosted.org/packages/1f/2c/22eee714d7199ae0464beda6ad5fedec8fee6a2f7ffd1e8f1840928fe318/isort-4.3.4-py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests<3,>=2->tidypy)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests<3,>=2->tidypy)
  Downloading https://files.pythonhosted.org/packages/8c/4b/5cbc4cb46095f369117dcb751821e1bef9dd86a07c968d8757e9204c324c/urllib3-1.24-py2.py3-none-any.whl (117kB)
    100% |████████████████████████████████| 122kB 2.1MB/s
Collecting certifi>=2017.4.17 (from requests<3,>=2->tidypy)
  Using cached https://files.pythonhosted.org/packages/56/9d/1d02dd80bc4cd955f98980f28c5ee2200e1209292d5f9e9cc8d030d18655/certifi-2018.10.15-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<3,>=2->tidypy)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting GitPython>=1.0.1 (from bandit<2,>=1.4->tidypy)
  Using cached https://files.pythonhosted.org/packages/fe/e5/fafe827507644c32d6dc553a1c435cdf882e0c28918a5bab29f7fbebfb70/GitPython-2.1.11-py2.py3-none-any.whl
Collecting stevedore>=1.20.0 (from bandit<2,>=1.4->tidypy)
  Using cached https://files.pythonhosted.org/packages/35/fa/8683fab2a6e15ecfe107996e56fab91e52fe3ec0b40ca9440a0e1ffe6892/stevedore-1.30.0-py2.py3-none-any.whl
Collecting flake8 (from flake8-polyfill<2,>=1.0.2->pep8-naming<0.8,>=0.4->tidypy)
  Using cached https://files.pythonhosted.org/packages/34/a6/49e2849a0e5464e1b5d621f63bc8453066f0f367bb3b744a33fca0bc1ddd/flake8-3.6.0-py2.py3-none-any.whl
Collecting wrapt (from astroid>=2.0.0->pylint<2.2,>=2; python_version >= "3.4"->tidypy)
Collecting lazy-object-proxy (from astroid>=2.0.0->pylint<2.2,>=2; python_version >= "3.4"->tidypy)
Collecting gitdb2>=2.0.0 (from GitPython>=1.0.1->bandit<2,>=1.4->tidypy)
  Using cached https://files.pythonhosted.org/packages/da/30/a407568aa8d8f25db817cf50121a958722f3fc5f87e3a6fba1f40c0633e3/gitdb2-2.0.5-py2.py3-none-any.whl
Collecting pbr!=2.1.0,>=2.0.0 (from stevedore>=1.20.0->bandit<2,>=1.4->tidypy)
  Using cached https://files.pythonhosted.org/packages/76/0c/304d968fe010ba7c2ecc1d57e28741ddd3a305439dcf1cdb3b6f896a3c00/pbr-5.1.0-py2.py3-none-any.whl
Collecting smmap2>=2.0.0 (from gitdb2>=2.0.0->GitPython>=1.0.1->bandit<2,>=1.4->tidypy)
  Using cached https://files.pythonhosted.org/packages/55/d2/866d45e3a121ee15a1dc013824d58072fd5c7799c9c34d01378eb262ca8f/smmap2-2.0.5-py2.py3-none-any.whl
flake8 3.6.0 has requirement pycodestyle<2.5.0,>=2.4.0, but you'll have pycodestyle 2.3.1 which is incompatible.
flake8 3.6.0 has requirement pyflakes<2.1.0,>=2.0.0, but you'll have pyflakes 1.6.0 which is incompatible.
Installing collected packages: tqdm, pydiatra, iso8601, six, basicserial, docutils, pyroma, unidiff, pyyaml, detect-secrets, check-manifest, pyflakes, restructuredtext-lint, polib, click, dennis, vulture, demjson, pytoml, snowballstemmer, pydocstyle, pycodestyle, pathspec, yamllint, mccabe, flake8, flake8-polyfill, pep8-naming, wrapt, lazy-object-proxy, astroid, isort, pylint, idna, urllib3, certifi, chardet, requests, smmap2, gitdb2, GitPython, pbr, stevedore, bandit, tidypy
tidypySuccessfully installed GitPython-2.1.11 astroid-2.0.4 bandit-1.5.1 basicserial-0.1.0 certifi-2018.10.15 chardet-3.0.4 check-manifest-0.37 click-7.0 demjson-2.2.4 dennis-0.9 detect-secrets-0.10.4 docutils-0.14 flake8-3.6.0 flake8-polyfill-1.0.2 gitdb2-2.0.5 idna-2.7 iso8601-0.1.12 isort-4.3.4 lazy-object-proxy-1.3.1 mccabe-0.6.1 pathspec-0.5.9 pbr-5.1.0 pep8-naming-0.7.0 polib-1.1.0 pycodestyle-2.3.1 pydiatra-0.12.4 pydocstyle-2.1.1 pyflakes-1.6.0 pylint-2.1.1 pyroma-2.4 pytoml-0.1.19 pyyaml-3.13 requests-2.20.0 restructuredtext-lint-1.1.3 six-1.11.0 smmap2-2.0.5 snowballstemmer-1.2.1 stevedore-1.30.0 tidypy-0.6.0 tqdm-4.28.1 unidiff-0.5.5 urllib3-1.24 vulture-0.29 wrapt-1.10.11 yamllint-1.12.1
aa:~/git/repo [branch]$ tidypy
Traceback (most recent call last):
  File "/Users/aa/.virtualenvs/repo/bin/tidypy", line 7, in <module>
    from tidypy.cli import main
  File "/Users/aa/.virtualenvs/repo/lib/python3.7/site-packages/tidypy/cli.py", line 66, in <module>
    for name, cls in iteritems(get_tools())
  File "/Users/aa/.virtualenvs/repo/lib/python3.7/site-packages/tidypy/config.py", line 35, in get_tools
    get_tools._CACHE[entry.name] = entry.load()
  File "/Users/aa/.virtualenvs/repo/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2331, in load
    self.require(*args, **kwargs)
  File "/Users/aa/.virtualenvs/repo/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2354, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/Users/aa/.virtualenvs/repo/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pycodestyle 2.3.1 (/Users/aa/.virtualenvs/repo/lib/python3.7/site-packages), Requirement.parse('pycodestyle<2.5.0,>=2.4.0'), {'flake8'})```

**Comment by jayclassless** [comment]
Yea, flake8 just made a release that tossed a wrench in our works. I'll try to have a fix out tonight.

Dependency hell strikes again. :(

**Comment by jayclassless** [comment]
New version published that should solve this. Let me know if problems persist.

**Comment by samuelhwilliams** [comment]
Awesome. Thanks! 👍

Was this caused by flake8 publishing a backwards-incompatible change without bumping versions correctly, or could this be solved by stricter dependency management on tidypy? Happy to brainstorm ideas if the latter - unless you already have a plan in place.

**Comment by jayclassless** [comment]
flake8 didn't really do anything wrong, tidypy was just a victim of pip's limited ability to solve non-trivial dependency graphs.

Below are snippets from the output of ``pipenv graph`` for versions 0.6 and 0.7 of tidypy. tidypy depends on pycodestyle and pep8-naming. pep8-naming dependency chain includes a very loose dependency on flake8. When pip went to install flake8, it grabbed the newest, which requires a version of pycodestyle that was outside the bounds that tidypy wanted -- thus the error.

v0.6.0:
```
  - pep8-naming [required: >=0.4,<0.8, installed: 0.7.0]
    - flake8-polyfill [required: >=1.0.2,<2, installed: 1.0.2]
      - flake8 [required: Any, installed: 3.5.0]
        - configparser [required: Any, installed: 3.5.0]
        - enum34 [required: Any, installed: 1.1.6]
        - mccabe [required: >=0.6.0,<0.7.0, installed: 0.6.1]
        - pycodestyle [required: >=2.0.0,<2.4.0, installed: 2.3.1]
        - pyflakes [required: >=1.5.0,<1.7.0, installed: 1.6.0]
  - pycodestyle [required: >=2.3,<2.4, installed: 2.3.1]
```

v0.7.0:
```
  - pep8-naming [required: >=0.4,<0.8, installed: 0.7.0]
    - flake8-polyfill [required: >=1.0.2,<2, installed: 1.0.2]
      - flake8 [required: Any, installed: 3.6.0]
        - configparser [required: Any, installed: 3.5.0]
        - enum34 [required: Any, installed: 1.1.6]
        - mccabe [required: >=0.6.0,<0.7.0, installed: 0.6.1]
        - pycodestyle [required: >=2.4.0,<2.5.0, installed: 2.4.0]
        - pyflakes [required: >=2.0.0,<2.1.0, installed: 2.0.0]
        - setuptools [required: >=30, installed: 40.4.3]
  - pycodestyle [required: >=2.4,<2.5, installed: 2.4.0]
```

I thought about explicitly pinning flake8 in tidypy's dependencies to something known to be safe, but something feels dirty about forcing a dependency on something tidypy doesn't actually depend on. Also, it feels like a slippery slope, as there are other packages that could potentially cause the same sorts of issues (enum34, configparser, mccabe, etc), and pinning the entire tree feels bad, too.

I'm definitely open to suggestions, but I'd like to avoid things like vendoring everything or pinning the full dependency tree. For the time being, I've updated the cron on Travis to do a build every day, so if a release does sneak by that breaks tidypy, I'll at least get a notification.
