### ISSUE TITLE
AttributeError: 'TidyPyVulture' object has no attribute 'noqa_lines'

### ISSUE THREAD

**Issue by scottj97** [jayclassless/tidypy#40]
It seems that Vulture 1.5 (released 2020-05-24) has broken TidyPy.

# Error messages
```
    1     vulture: Unexpected exception:
          Traceback (most recent call last):
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/tidypy/core.py", line 53, in run
              issues = impl.execute(finder)
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/tidypy/tools/vulture.py", line 130, in execute
              self.vulture.scavenge(finder)
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/tidypy/tools/vulture.py", line 58, in scavenge
              self.scan(source, filename=filepath)
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/tidypy/tools/vulture.py", line 73, in scan
              self.visit(node)
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/vulture/core.py", line 629, in visit
              return self.generic_visit(node)
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/vulture/core.py", line 663, in generic_visit
              self.visit(item)
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/vulture/core.py", line 628, in visit
              visitor(node)
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/vulture/core.py", line 573, in visit_FunctionDef
              self._define(
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/vulture/core.py", line 497, in _define
              if ignored(first_lineno):
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/vulture/core.py", line 490, in ignored
              or noqa.ignore_line(self.noqa_lines, lineno, ERROR_CODES[typ])
          AttributeError: 'TidyPyVulture' object has no attribute 'noqa_lines'
          (tidypy:tool)
```

# Root cause

This [change in Vulture](https://github.com/jendrikseipp/vulture/commit/219653783572930c5db936546ce1d07b65411470) added a new attribute `noqa_lines` to the `Vulture.scan()` method, which is unfortunately copy-pasted into TidyPyVulture, which is now out of date.

# Full log

```
$ mkdir src
$ echo 'if True: X = 1' > src/run.py
$ python3 -V
Python 3.8.0
$ python3 -m venv venv
$ ./venv/bin/pip3 install tidypy
Collecting tidypy
  Using cached https://files.pythonhosted.org/packages/c9/4f/78b8287c188a092fd6453f0f6786b7f33103c8a602fd95fe02b41e263806/tidypy-0.14.0-py3-none-any.whl
Collecting pydocstyle<6,>=4 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/cc/fb/0662498401c663606ef35b4ec6a0aca6b4121d6da8c3ac40a4e68f6ac521/pydocstyle-5.0.2-py3-none-any.whl
Collecting basicserial<2.0,>=0.1 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/6e/52/e619e85211cad107dd002f0060ae158c48411c272f99acaef611a6678e86/basicserial-1.1.0-py3-none-any.whl
Collecting click<8,>=6 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Collecting restructuredtext-lint<2,>=1.1 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/36/a6/507be0d9125cd37530e96062b7f838ee1777a0e30855197964603da7b990/restructuredtext_lint-1.3.1.tar.gz
Collecting pylint<2.6,>=2 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/e8/fb/734960c55474c8f74e6ad4c8588fc44073fb9d69e223269d26a3c2435d16/pylint-2.5.3-py3-none-any.whl
Collecting bandit<2,>=1.4 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/5a/50/ff2f2c8f1f0ca1569f678eeb608c0f973b835985410985594fbee96be820/bandit-1.6.2-py2.py3-none-any.whl
Collecting detect-secrets<0.14,>=0.11.3 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/15/95/f6bada839f3446f6e279bcf7675eae6ec456b652617fbaaad70642f6d3e5/detect_secrets-0.13.1-py2.py3-none-any.whl
Collecting check-manifest<0.42,>=0.37 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/54/40/7faf80474b21b3bd3f97465a31c3204379827379c5017f5cc703eee576ec/check_manifest-0.41-py2.py3-none-any.whl
Collecting requests<3,>=2 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl
Collecting tqdm<5,>=4.11 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/46/62/7663894f67ac5a41a0d8812d78d9d2a9404124051885af9d77dc526fb399/tqdm-4.47.0-py2.py3-none-any.whl
Collecting pycodestyle<2.7,>=2.4 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/10/5b/88879fb861ab79aef45c7e199cae3ef7af487b5603dcb363517a50602dd7/pycodestyle-2.6.0-py2.py3-none-any.whl
Collecting pyyaml<6,>=3.12 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz
Collecting toml<0.11,>=0.10 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/9f/e1/1b40b80f2e1663a6b9f497123c11d7d988c0919abbf3c3f2688e448c5363/toml-0.10.1-py2.py3-none-any.whl
Collecting pep8-naming<0.11,>=0.4 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/5b/69/6018efb8ae18bd5a05f5f447666060a44aa8fe017f439c50fe8c8bd990cf/pep8_naming-0.10.0-py2.py3-none-any.whl
Collecting mccabe<0.7,>=0.6 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting pydiatra<0.13,>=0.12.2 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/43/83/5717f46f837ebc40414f6f0342534c9ddf9c9abd0455ab708cb93b021d76/pydiatra-0.12.5.tar.gz
Collecting eradicate<2,>=1 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/65/ed/5b4506e122114f9439482d2a810ade4aa06cc4e306185931889e58b47f46/eradicate-1.0.tar.gz
Collecting pyflakes<2.3,>=1.5 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/69/5b/fd01b0c696f2f9a6d2c839883b642493b431f28fa32b29abc465ef675473/pyflakes-2.2.0-py2.py3-none-any.whl
Collecting vulture<2,>=1.1 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/b4/6a/df844d624e1e1f8a01873268850ac0976bf930164bfca141c103d39308ce/vulture-1.5-py2.py3-none-any.whl
Collecting pyroma<3,>=2.2 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/74/67/9f162a493011a3235761ea980a5ead7de189fb40c955da7555e7c82e2b20/pyroma-2.6-py2.py3-none-any.whl
Collecting dennis<1,>=0.9 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/2d/2e/2cb43a5e787387b558d2eeefc2713305d2df97c4622cee37b1e6f5505031/dennis-0.9-py2.py3-none-any.whl
Collecting demjson<3,>=2.2.4 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/96/67/6db789e2533158963d4af689f961b644ddd9200615b8ce92d6cad695c65a/demjson-2.2.4.tar.gz
Collecting yamllint<2,>=1.8 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/9e/e5/1895d308f95e44104472205df81dd6e68f326d4887c7502b90436c5bc91e/yamllint-1.23.0-py2.py3-none-any.whl
Collecting dlint<0.11,>=0.8 (from tidypy)
  Using cached https://files.pythonhosted.org/packages/cb/78/9a3fb63fe943d3c8d47d3fdcabcfa8ed2bbe4de80eb95d550bcdb4735342/dlint-0.10.3-py2.py3-none-any.whl
Collecting snowballstemmer (from pydocstyle<6,>=4->tidypy)
  Using cached https://files.pythonhosted.org/packages/7d/4b/cdf1113a0e88b641893b814e9c36f69a6fda28cd88b62c7f0d858cde3166/snowballstemmer-2.0.0-py2.py3-none-any.whl
Collecting iso8601 (from basicserial<2.0,>=0.1->tidypy)
  Using cached https://files.pythonhosted.org/packages/ef/57/7162609dab394d38bbc7077b7ba0a6f10fb09d8b7701ea56fa1edc0c4345/iso8601-0.1.12-py2.py3-none-any.whl
Collecting docutils<1.0,>=0.11 (from restructuredtext-lint<2,>=1.1->tidypy)
  Using cached https://files.pythonhosted.org/packages/81/44/8a15e45ffa96e6cf82956dd8d7af9e666357e16b0d93b253903475ee947f/docutils-0.16-py2.py3-none-any.whl
Collecting astroid<=2.5,>=2.4.0 (from pylint<2.6,>=2->tidypy)
  Using cached https://files.pythonhosted.org/packages/24/a8/5133f51967fb21e46ee50831c3f5dda49e976b7f915408d670b1603d41d6/astroid-2.4.2-py3-none-any.whl
Collecting isort<5,>=4.2.5 (from pylint<2.6,>=2->tidypy)
  Using cached https://files.pythonhosted.org/packages/e5/b0/c121fd1fa3419ea9bfd55c7f9c4fedfec5143208d8c7ad3ce3db6c623c21/isort-4.3.21-py2.py3-none-any.whl
Collecting stevedore>=1.20.0 (from bandit<2,>=1.4->tidypy)
  Using cached https://files.pythonhosted.org/packages/45/62/aa4c77e0f0899b7697445d8126fd099473452488d70f877426812c2ce982/stevedore-2.0.1-py3-none-any.whl
Collecting six>=1.10.0 (from bandit<2,>=1.4->tidypy)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting GitPython>=1.0.1 (from bandit<2,>=1.4->tidypy)
  Using cached https://files.pythonhosted.org/packages/8c/f9/c315aa88e51fabdc08e91b333cfefb255aff04a2ee96d632c32cb19180c9/GitPython-3.1.3-py3-none-any.whl
Collecting pep517 (from check-manifest<0.42,>=0.37->tidypy)
  Using cached https://files.pythonhosted.org/packages/43/f6/4af3567c136e8e1620f6fcff665f9a478e68d06f9c990d0f2717cf9a2b8c/pep517-0.8.2-py2.py3-none-any.whl
Collecting chardet<4,>=3.0.2 (from requests<3,>=2->tidypy)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests<3,>=2->tidypy)
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3,>=2->tidypy)
  Using cached https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests<3,>=2->tidypy)
  Using cached https://files.pythonhosted.org/packages/e1/e5/df302e8017440f111c11cc41a6b432838672f5a70aa29227bf58149dc72f/urllib3-1.25.9-py2.py3-none-any.whl
Collecting flake8-polyfill<2,>=1.0.2 (from pep8-naming<0.11,>=0.4->tidypy)
  Using cached https://files.pythonhosted.org/packages/86/b5/a43fed6fd0193585d17d6faa7b85317d4461f694aaed546098c69f856579/flake8_polyfill-1.0.2-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./venv/lib/python3.8/site-packages (from pyroma<3,>=2.2->tidypy) (41.2.0)
Collecting pygments (from pyroma<3,>=2.2->tidypy)
  Using cached https://files.pythonhosted.org/packages/2d/68/106af3ae51daf807e9cdcba6a90e518954eb8b70341cee52995540a53ead/Pygments-2.6.1-py3-none-any.whl
Collecting polib>=1.0.8 (from dennis<1,>=0.9->tidypy)
  Using cached https://files.pythonhosted.org/packages/30/a2/e407c3b00cace3d7fc8df14d364deeecfeb96044e1a317de583bc26eae58/polib-1.1.0-py2.py3-none-any.whl
Collecting pathspec>=0.5.3 (from yamllint<2,>=1.8->tidypy)
  Using cached https://files.pythonhosted.org/packages/5d/d0/887c58853bd4b6ffc7aa9cdba4fc57d7b979b45888a6bd47e4568e1cf868/pathspec-0.8.0-py2.py3-none-any.whl
Collecting flake8<4.0.0,>=3.6.0 (from dlint<0.11,>=0.8->tidypy)
  Using cached https://files.pythonhosted.org/packages/6c/20/6326a9a0c6f0527612bae748c4c03df5cd69cf06dfb2cf59d85c6e165a6a/flake8-3.8.3-py2.py3-none-any.whl
Collecting wrapt~=1.11 (from astroid<=2.5,>=2.4.0->pylint<2.6,>=2->tidypy)
Collecting lazy-object-proxy==1.4.* (from astroid<=2.5,>=2.4.0->pylint<2.6,>=2->tidypy)
  Using cached https://files.pythonhosted.org/packages/34/8c/74acd0ad5a0518be9e0f3b4d022e84da0c1d9b78972afce73259ac85d78b/lazy_object_proxy-1.4.3-cp38-cp38-manylinux1_x86
_64.whl
Collecting pbr!=2.1.0,>=2.0.0 (from stevedore>=1.20.0->bandit<2,>=1.4->tidypy)
  Using cached https://files.pythonhosted.org/packages/96/ba/aa953a11ec014b23df057ecdbc922fdb40ca8463466b1193f3367d2711a6/pbr-5.4.5-py2.py3-none-any.whl
Collecting gitdb<5,>=4.0.1 (from GitPython>=1.0.1->bandit<2,>=1.4->tidypy)
  Using cached https://files.pythonhosted.org/packages/48/11/d1800bca0a3bae820b84b7d813ad1eff15a48a64caea9c823fc8c1b119e8/gitdb-4.0.5-py3-none-any.whl
Collecting smmap<4,>=3.0.1 (from gitdb<5,>=4.0.1->GitPython>=1.0.1->bandit<2,>=1.4->tidypy)
  Using cached https://files.pythonhosted.org/packages/b0/9a/4d409a6234eb940e6a78dfdfc66156e7522262f5f2fecca07dc55915952d/smmap-3.0.4-py2.py3-none-any.whl
Installing collected packages: snowballstemmer, pydocstyle, iso8601, basicserial, click, docutils, restructuredtext-lint, mccabe, six, wrapt, lazy-object-proxy, astroid, 
isort, toml, pylint, pbr, stevedore, pyyaml, smmap, gitdb, GitPython, bandit, chardet, idna, certifi, urllib3, requests, detect-secrets, pep517, check-manifest, tqdm, pyc
odestyle, pyflakes, flake8, flake8-polyfill, pep8-naming, pydiatra, eradicate, vulture, pygments, pyroma, polib, dennis, demjson, pathspec, yamllint, dlint, tidypy
  Running setup.py install for restructuredtext-lint: started
    Running setup.py install for restructuredtext-lint: finished with status 'done'
  Running setup.py install for pyyaml: started
    Running setup.py install for pyyaml: finished with status 'done'
  Running setup.py install for pydiatra: started
    Running setup.py install for pydiatra: finished with status 'done'
  Running setup.py install for eradicate: started
    Running setup.py install for eradicate: finished with status 'done'
  Running setup.py install for demjson: started
    Running setup.py install for demjson: finished with status 'done'
Successfully installed GitPython-3.1.3 astroid-2.4.2 bandit-1.6.2 basicserial-1.1.0 certifi-2020.6.20 chardet-3.0.4 check-manifest-0.41 click-7.1.2 demjson-2.2.4 dennis-0
.9 detect-secrets-0.13.1 dlint-0.10.3 docutils-0.16 eradicate-1.0 flake8-3.8.3 flake8-polyfill-1.0.2 gitdb-4.0.5 idna-2.10 iso8601-0.1.12 isort-4.3.21 lazy-object-proxy-1
.4.3 mccabe-0.6.1 pathspec-0.8.0 pbr-5.4.5 pep517-0.8.2 pep8-naming-0.10.0 polib-1.1.0 pycodestyle-2.6.0 pydiatra-0.12.5 pydocstyle-5.0.2 pyflakes-2.2.0 pygments-2.6.1 py
lint-2.5.3 pyroma-2.6 pyyaml-5.3.1 requests-2.24.0 restructuredtext-lint-1.3.1 six-1.15.0 smmap-3.0.4 snowballstemmer-2.0.0 stevedore-2.0.1 tidypy-0.14.0 toml-0.10.1 tqdm
-4.47.0 urllib3-1.25.9 vulture-1.5 wrapt-1.12.1 yamllint-1.23.0
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
$ (cd src && ../venv/bin/tidypy check)
Analyzing |██▉       |  29% [00:00, current=bandit,eradicate,polint,pycodestyle]
Analyzing |███████   |  71% [00:00, current=pycodestyle,pylint,sec,pylint,secrets]  
Analyzing |██████████| 100% [00:00]                                             
Analyzing |██████████| 100% [00:00]. (1)
    1     vulture: Unexpected exception:
          Traceback (most recent call last):
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/tidypy/core.py", line 53, in run
              issues = impl.execute(finder)
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/tidypy/tools/vulture.py", line 130, in execute
              self.vulture.scavenge(finder)
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/tidypy/tools/vulture.py", line 58, in scavenge
              self.scan(source, filename=filepath)
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/tidypy/tools/vulture.py", line 73, in scan
              self.visit(node)
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/vulture/core.py", line 629, in visit
              return self.generic_visit(node)
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/vulture/core.py", line 663, in generic_visit
              self.visit(item)
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/vulture/core.py", line 628, in visit
              visitor(node)
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/vulture/core.py", line 585, in visit_If
              self._handle_conditional_node(node, "if")
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/vulture/core.py", line 435, in _handle_conditional_node
              self._define(
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/vulture/core.py", line 497, in _define
              if ignored(first_lineno):
            File "/home/sjohnson/python-play/venv/lib/python3.8/site-packages/vulture/core.py", line 490, in ignored
              or noqa.ignore_line(self.noqa_lines, lineno, ERROR_CODES[typ])
          AttributeError: 'TidyPyVulture' object has no attribute 'noqa_lines'
          (tidypy:tool)

run.py (5)
    1     Missing docstring in public module (pydocstyle:D100)
    1     Missing module docstring (pylint:missing-module-docstring)
    1     Using a conditional statement with a constant value (pylint:using-constant-test)
    1:8   multiple statements on one line (colon) (pycodestyle:E701)
    1:10  More than one statement on a single line (pylint:multiple-statements)

✗ 6 issues found.
```

**Comment by jayclassless** [comment]
Thanks for the report. Should be fixed in the latest release.

**Comment by scottj97** [comment]
Excellent! I confirm this fixes the issue I was seeing, and tidypy (and all its sub-components) allows all Python 3.8 new syntax (positional-only arguments, walrus operator).
