### ISSUE TITLE
Yamllint error when enabling "key-ordering" and disabling "line-length"

### ISSUE THREAD

**Issue by pespinel** [jayclassless/tidypy#49]
Config:

```
[yamllint]
use = true
filters = ["\\.yaml$", "\\.yml$",]
disabled = [
  "line-length",
  "document-start",
]

[yamllint.options]
key-ordering = "enable"
```

Error:
```
    1     yamllint: Unexpected exception:
          Traceback (most recent call last):
            File "/Users/Pablo/workspace/novum-tests/lib/python3.9/site-packages/yamllint/config.py", line 77, in parse
              conf = yaml.safe_load(raw_content)
            File "/Users/Pablo/workspace/novum-tests/lib/python3.9/site-packages/yaml/__init__.py", line 162, in safe_load
              return load(stream, SafeLoader)
            File "/Users/Pablo/workspace/novum-tests/lib/python3.9/site-packages/yaml/__init__.py", line 114, in load
              return loader.get_single_data()
            File "/Users/Pablo/workspace/novum-tests/lib/python3.9/site-packages/yaml/constructor.py", line 41, in get_single_data
              node = self.get_single_node()
            File "/Users/Pablo/workspace/novum-tests/lib/python3.9/site-packages/yaml/composer.py", line 39, in get_single_node
              if not self.check_event(StreamEndEvent):
            File "/Users/Pablo/workspace/novum-tests/lib/python3.9/site-packages/yaml/parser.py", line 98, in check_event
              self.current_event = self.state()
            File "/Users/Pablo/workspace/novum-tests/lib/python3.9/site-packages/yaml/parser.py", line 171, in parse_document_start
              raise ParserError(None, None,
          yaml.parser.ParserError: expected '<document start>', but found '<block mapping start>'
            in "<unicode string>", line 6, column 3:
                line-length: disable
                ^

          During handling of the above exception, another exception occurred:

          Traceback (most recent call last):
            File "/Users/Pablo/workspace/novum-tests/lib/python3.9/site-packages/tidypy/core.py", line 53, in run
              issues = impl.execute(finder)
            File "/Users/Pablo/workspace/novum-tests/lib/python3.9/site-packages/tidypy/tools/yamllint.py", line 73, in execute
              cfg = self.make_config()
            File "/Users/Pablo/workspace/novum-tests/lib/python3.9/site-packages/tidypy/tools/yamllint.py", line 69, in make_config
              return YamlLintConfig(cfg)
            File "/Users/Pablo/workspace/novum-tests/lib/python3.9/site-packages/yamllint/config.py", line 44, in __init__
              self.parse(content)
            File "/Users/Pablo/workspace/novum-tests/lib/python3.9/site-packages/yamllint/config.py", line 79, in parse
              raise YamlLintConfigError('invalid config: %s' % e)
          yamllint.config.YamlLintConfigError: invalid config: expected '<document start>', but found '<block mapping start>'
            in "<unicode string>", line 6, column 3:
                line-length: disable
                ^
          (tidypy:tool)
```

I also tried this, white the same result:

```
[yamllint]
use = true
filters = ["\\.yaml$", "\\.yml$",]

[yamllint.options]
key-ordering = "enable"
line-length = "disable"
document-start "disable"
```

**Comment by pespinel** [comment]
@jayclassless Am i doing something wrong?

**Comment by jayclassless** [comment]
You found an ugly bug. :) I just published a version that should handle this better.
